config/routes.rb
Rails.application.routes.draw do

  get 'search/create'

  devise_for :users
	resources "mantenimientos"
	resources "transacciones"
	root to: "mantenimientos#home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mantenimiento.rb
class Mantenimiento < ApplicationRecord
	belongs_to :user
	validates :codigo, presence: true, uniqueness: true
	validates :item, presence: true, uniqueness: true
	validates :sku, presence: true, length: {maximum: 20}
	validates :quantity, presence: true

end

app/models/transaccion.rb
class Transaccion < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :mantenimientos
  has_many :transacciones
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/mantenimientos_controller.rb
class MantenimientosController < ApplicationController
	before_action :find_params, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:index, :new, :edit]
	def index
		@mantenimientos = Mantenimiento.all
	end

	def new
		@mantenimiento = Mantenimiento.new
	end

	def create
		@mantenimiento = current_user.mantenimientos.new mantenimiento_params

		if @mantenimiento.save
			redirect_to @mantenimiento
		else
			render 'new'
		end
	end

	def show
		
	end

	def edit
	end

	def update
		if @mantenimiento.update mantenimiento_params
			redirect_to @mantenimiento
		else
			render 'edit'
		end
	end

	def destroy
		@mantenimiento.destroy
		redirect_to mantenimientos_path
	end

	private


	def mantenimiento_params
		params.require(:mantenimiento).permit(:codigo, :item, :sku, :minimum_quantity, :quantity, :status, :apartment, :users)
	end

	def find_params
		@mantenimiento = Mantenimiento.find(params[:id])
	end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def create
  	palabra = "%#{params[:keyword]}%"

    @mantenimientos = Mantenimiento.where("item LIKE ? OR sku LIKE ?", palabra,palabra)

    
  	respond_to do |format|
  		format.html {redirect_to root_path}
  		format.json {render json: @mantenimientos}
  		format.js
  	end
  end
end

app/controllers/transacciones_controller.rb
class TransaccionesController < ApplicationController
	before_action :authenticate_user!, only: [:index]
	layout "transaccion"
	def index
		@transacciones = Transaccion.all
	end

	def new
		@transaccion = Transaccion.new
	end

	def show
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/mantenimientos_helper.rb
module MantenimientosHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/transacciones_helper.rb
module TransaccionesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

	<title>TnB - Papeleria</title>
	<link href='http://fonts.googleapis.com/css?family=Raleway:400,700'	rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	
	<% if notice %>
		<div id="notice_wrapper">
			<p class="notice"><%= notice %></p>
		</div>
	<% elsif alert %>
		<div id="notice_wrapper">
			<p class="alert"><%= alert %></p>
		</div>
	<% end %>

  	<header id="main_navigation" class="clearfix">
		<%= link_to "Papeleria", root_path, class:"name" %>

		<nav>
			<%= link_to "Mantenimiento", mantenimientos_path %>
			<%= link_to "Transaccion", transacciones_path %>
			<a href="#">Contacto</a>
			<% if user_signed_in? %>
				<%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete %>
			<% else %>
				<%= link_to "Iniciar Sesion", new_user_session_path %>
				<%= link_to "Crear Cuenta", new_user_registration_path %>
			<% end %>
		</nav>
	</header>

    <%= yield %>

    <footer id="main_footer">
		<p class="copyright">&copy; 2016 Julio Garcia</p>
		<nav>
			<a href=""><i class="fa fa-envelope-o" aria-hidden="true"></i></a>
			<a href=""><i class="fa fa-github" aria-hidden="true"></i></a>
		</nav>
	</footer>

  </body>
</html>

app/views/layouts/transaccion.html.erb
<!DOCTYPE html>
<html>
  <head>

	<title>TnB - Papeleria</title>
	<link href='http://fonts.googleapis.com/css?family=Raleway:400,700'	rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<header id="main_navigation" class="clearfix">
		<%= link_to "Papeleria", root_path, class:"name" %>

		<nav>
			<%= link_to "Mantenimiento", mantenimientos_path %>
			<%= link_to "Transaccion", transacciones_path %>
			<a href="#">Contacto</a>
			<% if user_signed_in? %>
				<%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete %>
			<% else %>
				<%= link_to "Iniciar Sesion", new_user_session_path %>
				<%= link_to "Crear Cuenta", new_user_registration_path %>
			<% end %>
		</nav>
	</header>
	
	<div id="sidebar">
		<ul>
			<li class="category">Tipos de Transaccion</li>
			<li><a href="/transacciones/entradas">Entradas</a></li>
			<li><a href="/transacciones/salidas">Salidas</a></li>
		</ul>
		<p class="name-julio">&copy; 2016 Julio Garcia</p>
	</div>

    <%= yield %>

  </body>
</html>

app/views/mantenimientos/_form.html.erb
<%= form_for(@mantenimiento) do |f| %>
  <% @mantenimiento.errors.full_messages.each do |message| %>
    <div class="error">
      <%= message %>
    </div>
  <% end %>
  <div class="modify">
  	<br>
  	<br>

  	<%= f.label :codigo, "Ingresa el Codigo" %><br>
  	<%= f.number_field :codigo, class:"forms" %>

  	<br>
  	<br>

	<%= f.label :item, "Escribe el Producto" %><br>
	<%= f.text_field :item, class:"forms"%>

	<br>
	<br>

	<%= f.label :sku, "SKU" %> <br>
	<%= f.number_field :sku, class:"forms" %>

	<br>
	<br>

	<%= f.label :minimum_quantity, "Cantidad Minima" %><br>
	<%= f.number_field :minimum_quantity, class:"forms" %>

	<br>
	<br>
	
	<%= f.label :quantity, "Cantidad"%> <br>
	<%= f.number_field :quantity, class:"forms"%>

	<br>
	<br>

	<%= f.label :apartment, "Categoria del Producto" %> <br>
	
	<%= f.select(:apartment) do %>
		<% [["Papeleria", "Papeleria"], ["Cartuchos", "Cartuchos"], ["Toner", "Toner"]].each do |t|%>
			<%= content_tag(:option, t.first, value: t.last) %>
		<% end %>
	<% end %>

	<br>
	<br>
	
	<%= f.label :status, "Status" %> <br>

	<%= f.select(:status) do %>
	  <% [["Activo", "Activo"],["Inactivo","Inactivo"]].each do |s| %>
	    <%= content_tag(:option, s.first, value: s.last) %>
	  <% end %>	
	<% end %>

	<br>
	<br>

	<%= f.submit "Guardar", class:"btn" %>
  </div>

<%end%>

app/views/mantenimientos/_mantenimiento.html.erb
<% if :keyword == mantenimiento %>
	<%= link_to "Nuevo Producto" , new_mantenimiento_path %>
	<h1>hola</h1>
<%else%>
	<div>
		<strong><%= mantenimiento.item %></strong>
		<%= mantenimiento.sku %>
		<%= mantenimiento.quantity %>
		<%= mantenimiento.apartment %>
		<%= mantenimiento.status %>
		<%= link_to "Ver Producto", mantenimiento%>
	</div>

<%end%>

app/views/mantenimientos/edit.html.erb
<h1>Editar Producto</h1>
<%= form_for(@mantenimiento) do |f| %>
  <% @mantenimiento.errors.full_messages.each do |message| %>
    <div class="error">
      <%= message %>
    </div>
  <% end %>
  <div class="modify">
  	<br>
  	<br>

  	<%= f.label :codigo, "Ingresa el Codigo" %><br>
  	<%= f.number_field :codigo, class:"forms" %>

  	<br>
  	<br>

	<%= f.label :item, "Escribe el Producto" %><br>
	<%= f.text_field :item, class:"forms"%>

	<br>
	<br>

	<%= f.label :sku, "SKU" %> <br>
	<%= f.number_field :sku, class:"forms" %>

	<br>
	<br>

	<%= f.label :minimum_quantity, "Cantidad Minima" %><br>
	<%= f.number_field :minimum_quantity, class:"forms" %>

	<br>
	<br>

	<%= f.label :apartment, "Categoria del Producto" %> <br>
	
	<%= f.select(:apartment) do %>
		<% [["Papeleria", "Papeleria"], ["Cartuchos", "Cartuchos"], ["Toner", "Toner"]].each do |t|%>
			<%= content_tag(:option, t.first, value: t.last) %>
		<% end %>
	<% end %>

	<br>
	<br>
	
	<%= f.label :status, "Status" %> <br>

	<%= f.select(:status) do %>
	  <% [["Activo", "Activo"],["Inactivo","Inactivo"]].each do |s| %>
	    <%= content_tag(:option, s.first, value: s.last) %>
	  <% end %>	
	<% end %>

	<br>
	<br>

	<%= f.submit "Guardar", class:"btn" %>
  </div>

<%end%>

app/views/mantenimientos/home.html.erb
<div id="resultados">
	<%= link_to "Nuevo Producto" , new_mantenimiento_path %>
</div>

<%= form_tag "/search/create", method: :get, remote: true do %>
	<div class="search">
		<%= text_field_tag :keyword, nil, placeholder:"Search", class:"forms move" %>
		<%= content_tag :button, type: :submit, class:"form" do %>
			.
		<%end%>
	</div>
<% end %>

app/views/mantenimientos/index.html.erb
<div>
	<table>
		<thead>
			<tr>
				<th>Codigo</th>
				<th>Item</th>
				<th>SKU</th>
				<th>Cantidad Minima</th>
				<th>Cantidad</th>
				<th>Departamento</th>
				<th>Status</th>
			</tr>
		</thead>

		<tbody>
			<% @mantenimientos.each do |mantenimiento| %>
				<tr>
					<td><%= mantenimiento.codigo %></td>
					<td><%= mantenimiento.item %></td>
					<td><%= mantenimiento.sku %></td>
					<td><%= mantenimiento.minimum_quantity %></td>
					<td><%= mantenimiento.quantity %></td>
					<td><%= mantenimiento.apartment %></td>
					<td><%= mantenimiento.status %></td>
					<td><%= link_to "Edit", edit_mantenimiento_path(mantenimiento), class:"link"%></td>
					<td><%= link_to "Delete", mantenimiento, method: :delete, data: {confirm: "Estas seguro de eliminar el producto"}, class:"link" %></td>
				</tr>
			<% end %>
		</tbody>
	</table>	
</div>

app/views/mantenimientos/new.html.erb
<h1>Nuevo Producto</h1>
<%= render "form" %>

app/views/mantenimientos/show.html.erb
<div class="modify-show">
	<h4>Codigo: <%= @mantenimiento.codigo %></h4>
	<h4>Producto: <%= @mantenimiento.item %></h4>
	<h5>SKU: <%= @mantenimiento.sku %></h5>
	<h5>Cantidad Minima: <%= @mantenimiento.minimum_quantity %></h5>
	<h5>Cantidad: <%= @mantenimiento.quantity %></h5>
	<h5>Categoria: <%= @mantenimiento.apartment %></h5>
	<h5>Status: <%= @mantenimiento.status %></h5>
	<p class="date"><%= @mantenimiento.created_at.strftime("%A, %b %d") %></p>
	<% unless @mantenimiento.user.nil? %>
		<p>Creado por: <%= @mantenimiento.user.email %></p>
	<% end %>
	<br>

	<%= link_to "Edit", edit_mantenimiento_path, class:"link"%>
	<%= link_to "Delete", mantenimiento_path, method: :delete, data: {confirm: "Estas seguro de eliminar el producto"}, class:"link" %>
</div>

app/views/transacciones/_form.html.erb
<%= form_for :transaccion do |f| %>
	<div class="contenedor">
		<div class="form-style-9">
			<%= f.text_field :item, placeholder:"Item", class:"forms"%>

			<%= f.number_field :quantity, placeholder:"Cantidad", class:"forms" %>

			<%= f.number_field :po, placeholder:"P.O", class:"forms" %>


			<%= f.submit "Guardar", class:"forms btn-trans" %>
		</div>
	</div>
	
<% end %>

app/views/transacciones/entradas.html.erb
<h1 class="hola">Entradas</h1>	

<%= render "form" %>

app/views/transacciones/index.html.erb
<h1 class="hola">Transacciones</h1>
	

app/views/transacciones/salidas.html.erb
<h1 class="hola">Salidas</h1>

<%= render "form" %>

app/views/transacciones/show.html.erb
<h1 class="hola">Entradas</h1>	

<%= render "form" %>